sudo: false

language: cpp

compiler:
  - clang
  - gcc

install:
  - mkdir build
  - cd build
  - cmake ..
  - make

script:
  - ctest -V

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.1
    - g++-5.1
    - clang-3.7